version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    deploy:
      restart_policy:
        condition: any
    ports:
      - "5432:5432"

  adonis_app:
    image: ${DOCKERHUB_USERNAME}/cocktails:latest
    depends_on:
      - postgres
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      PG_HOST: ${PG_HOST}
      APP_KEY: ${APP_KEY}
      PORT: ${PORT}
      HOST: ${HOST}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_PORT: ${DB_PORT}
      APP_DOMAIN: ${APP_DOMAIN}
      DRIVE_DISK: ${DRIVE_DISK}
    networks:
      - app_network
    ports:
    - "3333:3333"
    command: ["node", "./bin/server.js"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any


networks:
  app_network:
    driver: overlay
    ipam:
      config:
        - subnet: 10.20.0.0/24

volumes:
  postgres_data:
    driver: local
