version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cocktails
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    deploy:
      restart_policy:
        condition: any
    ports:
      - "5432:5432"

  adonis_app:
    image: meep00/adonis_app:latest
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: cocktails
      PG_HOST: postgres
    networks:
      - app_network
    ports:
    - "3333:3333"
    command: ["node", "./build/bin/server.js"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any


networks:
  app_network:
    driver: overlay

volumes:
  postgres_data:
    driver: local
